# ================================
# src/apps/graph_viewer/export.py
#
# Graph viewer가 서버 없이 읽을 수 있는 정적 그래프 export 파일을 생성합니다.
#
# Functions
#   - main() -> int : 스레드 그래프 스냅샷을 JavaScript export 파일로 씁니다.
# ================================

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from src.apps.graph_viewer.loader import build_graph_from_thread, list_threads


OUTPUT_PATH = Path("public/graph/export/graph_export.js")


def _js_string(payload: dict[str, Any]) -> str:
    """Return the JavaScript assignment text for a static graph export payload."""
    data = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    return (
        "/* Generated by src.apps.graph_viewer.export. Do not edit by hand. */\n"
        f"window.GRAPH_EXPORT={data};\n"
    )


def main() -> int:
    """Build graph snapshots for available threads and write the viewer export file."""
    threads = list_threads()
    snapshots: dict[str, Any] = {}
    errors: dict[str, str] = {}

    for thread in threads:
        thread_id = thread["id"]
        try:
            graph = build_graph_from_thread(thread_id)
        except Exception as exc:
            errors[thread_id] = str(exc)
            continue
        snapshots[thread_id] = graph.model_dump(by_alias=True)

    payload = {
        "version": 1,
        "threads": [thread for thread in threads if thread["id"] in snapshots],
        "snapshots": snapshots,
        "errors": errors,
    }
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(_js_string(payload), encoding="utf-8")

    print(f"[graph-export] wrote {OUTPUT_PATH} ({len(snapshots)}/{len(threads)} threads)")
    if errors:
        print(f"[graph-export] skipped {len(errors)} locked or unreadable threads")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
